# Generated by Django 3.2.7 on 2021-10-17 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211017_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
