# Generated by Django 3.2.7 on 2021-11-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211023_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_point',
        ),
    ]
