# Generated by Django 3.2.7 on 2022-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_user_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
